### ISSUE TITLE
Configure command not functional on linux 

### ISSUE THREAD

**Issue by 0Moey** [sourque/aeacus#132]
Aeacus Version="v1.8.3"
Linux Kernel="5.11.0-38-Generic"
Ubuntu Version="Ubuntu 20.04.3 LTS"

I was just poking around with the engine and trying to run **./aeacus configure** return: 
**[Warn] This is not implement on linux**

I have a valid scoring.conf and a valid TeamID

**Comment by sourque** [comment]
Hey, thanks for reporting this! We removed the script that used to be run by that option due to a couple unresolved issues with it. There are some other options ([such as the deprecated cerberus](https://github.com/elysium-suite/cerberus)), but none that are active. The best (and only recommended) way to configure aeacus at the moment is by editing the configuration text file. We'll remove the configure option and update the README soon.

**Comment by safinsingh** [comment]
I believe that this option has been removed
