### ISSUE TITLE
Release not working

### ISSUE THREAD

**Issue by jonathanxue5** [sourque/aeacus#156]
With the new aeacus binary, although the scoring works before release, when I use sudo ./aeacus --verbose release, all of the scoring doesn't work at all.

**Comment by jonathanxue5** [comment]
https://github.com/elysium-suite/aeacus/issues/154

**Comment by Mobmaker55** [comment]
Sorry, I suppose I should have clarified-- that was a test binary to fix it, not a permanent solution. Your `aeacus` and `phocus` binaries are out of sync, since they were not compiled at the same time. I recommend downloading [the latest release](https://github.com/elysium-suite/aeacus/releases/download/v2.0.4/aeacus-linux.zip) so your binaries in sync -- or pull the latest changes and compile it yourself, if that's more your tea.

Let me know if that fixes your problem!

**Comment by jonathanxue5** [comment]
I see, it works now. Thank you!
