### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by ShadowSchulme** [sourque/aeacus#162]
Hello, Can anyone tell me why or how i am getting this error message (its scoring feedback)? I am using Aeacus 2.0.3
panic: runtime error: slice bounds out of range [-3:]

goroutine 1 [running]:
main.runCheck({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...})
        /home/mob/GolandProjects/aeacus/checks.go:106 +0x7b3
main.checkPass(...)
        /home/mob/GolandProjects/aeacus/score.go:270
main.scoreCheck({{0xc00004e630, 0x8c}, 0x3, {0x0, 0x0, 0x0}, {0xc0002d38c0, 0x2, 0x2}, {0x0, ...}})
        /home/mob/GolandProjects/aeacus/score.go:217 +0x545
main.scoreChecks()
        /home/mob/GolandProjects/aeacus/score.go:194 +0x13d
main.scoreImage()
        /home/mob/GolandProjects/aeacus/score.go:115 +0x9f
main.main.func3(0xc000076000?)
        /home/mob/GolandProjects/aeacus/aeacus.go:72 +0x25
github.com/urfave/cli/v2.(*Command).Run(0xc000076000, 0xc0000584c0)
        /home/mob/go/pkg/mod/github.com/urfave/cli/v2@v2.14.0/command.go:173 +0x6ca
github.com/urfave/cli/v2.(*App).RunContext(0xc000072000, {0xc15c18?, 0xc00009a0a0}, {0xc0000c8000, 0x3, 0x4})
        /home/mob/go/pkg/mod/github.com/urfave/cli/v2@v2.14.0/app.go:384 +0xfde
github.com/urfave/cli/v2.(*App).Run(...)
        /home/mob/go/pkg/mod/github.com/urfave/cli/v2@v2.14.0/app.go:253
main.main()
        /home/mob/GolandProjects/aeacus/aeacus.go:163 +0xd3f

**Comment by sourque** [comment]
Hey, thanks for filing an issue. This kind of looks like you're missing a "type" for one of your checks, which should have been fixed (print a warning rather than crash) in dc02ae94afd4082d86741386e75e59cbea47aa56. Would you mind using the latest version and/or checking your config for missing values? If neither of those are it, if you could send a minimal config that reproduces the issue, that would be great.

**Comment by ShadowSchulme** [comment]
I accidentally had an extra [[check.pass]] oof. the new version 2.0.5 helped me figure it out. Thanks

However with this version, I am still running into another issue though. Is there any way to tell which policy is having trouble? its just weird cause the security policies all scored correctly before.
[INFO] Scoring image...
**[WARN] SecurityPolicy returned an error: SecurityPolicy item not found**
[WARN] Failed to open registry key: The system cannot find the file specified.
[WARN] RegistryKey returned an error: The system cannot find the file specified.
[WARN] Failed to open registry key: The system cannot find the file specified.
[WARN] RegistryKey returned an error: The system cannot find the file specified.
[WARN] Failed to open registry key: The system cannot find the file specified.
[WARN] RegistryKey returned an error: The system cannot find the file specified.
[WARN] Failed to open registry key: The system cannot find the file specified.
[WARN] RegistryKey returned an error: The system cannot find the file specified.
[WARN] Failed to open registry key: The system cannot find the file specified.
[WARN] RegistryKey returned an error: The system cannot find the file specified.
[WARN] Failed to open registry key: The system cannot find the file specified.
[WARN] RegistryKey returned an error: The system cannot find the file specified.
[WARN] Failed to open registry key: The system cannot find the file specified.
[WARN] RegistryKey returned an error: The system cannot find the file specified.
[WARN] Failed to open registry key: The system cannot find the file specified.

**Comment by sourque** [comment]
Glad to hear you got the crash fixed. Ah, yeah, we've improved the error reporting for RegistryKey in a dev branch (which we'll probably merge sometime soon), but the actual behavior shouldn't have changed. There's also no way to see which check caused a warning/error, short of removing items from the config and running it to see if it's still there, so that's a QoL update that we'll work on sometime soon as well.

That warning is printed whenever RegistryKey tries to open a path or key that doesn't exist (yet). Usually when the feature/secpol/whatever is enabled, the key/path is created and the warning goes away, which is why we only print that in verbose mode. But if you're finding the actual check results changed, and you didn't change the config at all, would you mind posting the check that works on 2.0.3 and doesn't on the latest?
