### ISSUE TITLE
Sending notification failed

### ISSUE THREAD

**Issue by tyliec** [sourque/aeacus#168]
Receiving the following error on a fresh install:

```
[WARN] TeamID.txt does not exist! This image is local only, so we will continue.
[FAIL] Sending notification failed. Is the user in the configuration correct, and are they logged in to a desktop environment?
```

![Screenshot 2023-07-03 at 1 53 40 PM](https://github.com/elysium-suite/aeacus/assets/15609358/2976b7f4-2853-4904-b4c1-03856657dcde)

**Comment by sourque** [comment]
The way we send notifications on Linux is pretty sketchy. The error you're receiving shouldn't prevent the engine from actually running, the user just won't get notifications.

In any case, how we do it is we run a shell script to export `DISPLAY` to be `:0`, try to find the correct `DBUS_SESSION_ADDRESS`, the run `notify-send`. Which should still work on XFCE, I'm thinking your `DISPLAY` is probably not `:0` since you're VNC'd in. 

Aeacus is usually running as a daemon, so the intelligent behavior would probably be to iterate through open displays and send a notification to all of them. This also sounds very sketchy and relies on using X displays, but such is the nature of Linux desktop envs.

Would you mind testing the DISPLAY hypothesis by running something like:

```
user=ubuntu
sudo -u $user DISPLAY=$DISPLAY \
              DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus \
              notify-send -i /opt/aeacus/assets/img/logo.png "Aeacus SE" "test notification"
```

**Comment by Mobmaker55** [comment]
bumping this, @tyliec if you have any more information that would be great!

**Comment by rasgajag** [comment]
I apologize for the notification everyone, but I fixed this issue you need to run the following command:
`sudo apt-get install libnotify-bin`
This is because libnotify-bin is a dependency, but is not expressly stated as one.
